apiVersion: v1
kind: Pod
metadata:
  name: my-secret-webapp
spec:
  containers:
   - name: my-secret-webapp
     image: mmumshad/simple-webapp-color
     envFrom:
       - secretRef:
           name: app-secret
