apiVersion: v1
kind: Pod
metadata:
  name: my-webapp
spec:
  containers:
    - name: my-webapp
      image: mmumshad/simple-webapp-color
      ports:
        - containerPort: 8080
  volumes:
      - name: app-config-volume
        configMap:
          name: app-config




